model:
  image_size: [224, 224]
  input_shape: [224, 224, 3]
  num_classes: 1
  architecture: simple_cnn

train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  optimizer: adam

data:
  train_split: 0.8
  val_split: 0.2
  shuffle: True
augmentation:
  horizontal_flip: True
  rotation_range: 15

seed: 42
